on:
    pull_request: null
    push:
        branches:
            - '*.*'

name: cs

jobs:
    phpunit:
        uses: spiral/gh-actions/.github/workflows/cs.yml@master
        with:
            os: >-
                ['ubuntu-latest']
            php: >-
                ['8.2']
