on:
    pull_request: null
    push:
        branches:
            - '*.*'

name: phpunit

jobs:
    phpunit:
        uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
        with:
            os: >-
                ['ubuntu-latest']
            php: >-
                ['8.1', '8.2', '8.3']
            stability: >-
                ['prefer-lowest', 'prefer-stable']
